-- MySQL Script generated by MySQL Workbench
-- Sat Oct 24 20:16:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rmrBoutique
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rmrBoutique
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rmrBoutique` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `rmrBoutique` ;



-- -----------------------------------------------------
-- Table `rmrBoutique`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmrBoutique`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmrBoutique`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmrBoutique`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmrBoutique`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmrBoutique`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `talle` INT UNSIGNED NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `discount` INT UNSIGNED NOT NULL,
  `id_categoria` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `idCategoria_idx` (`id_categoria` ASC),
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `rmrBoutique`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmrBoutique`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmrBoutique`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `remito` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuarios_idx` (`id_usuario` ASC) ,
  INDEX `idProductos_idx` (`id_producto` ASC) ,
  CONSTRAINT `idUsuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `rmrBoutique`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProductos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `rmrBoutique`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
